Dashboard navbar
Karmazynowe-Zyrafy/AngularWebClockClient pull request #1
Opened 2020-08-12 14:08 UTC by Czadzik

2020-08-12 21:53 UTC, ewelina-slepko requested changes
Nie uwzględniłam wszystkich wymagających poprawy fragmentów kodu w komentarzach, więc proszę żebyście zwrócili uwagę dodatkowo na:

- Formatowanie kodu, zbędne odstępy bądź ich brak.
- Używanie jednostek relatywnych (rem), zamiast absolutnych (px), używanie em tylko w uzasadnionych przypadkach
- Usunięcie lub opisanie zakomentowanych fragmentów kodu, 
- Trzymanie się spójnej konwencji nazewnictwa,
- Zamianę inline styles na klasy w CSS,
- Warto również prześledzić jeszcze raz kod w celu sprawdzenia czy nie ma w nim nieużywanego kodu, 
- Obmyślenie planu zastosowania media query.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/app.component.css
> +.bar{
Brak odstępu pomiędzy nazwą klasy a znacznikiem "{", pomimo że w wielu miejscach w CSSie ten odstęp występuje, świadczy o tym że prawdopodobnie nie korzystacie z żadnego narzędzia do formatowania kodu. Zwykle formatowanie można ustawić w konfiguracji programu z którego korzystacie i często są na to skróty klawiszowe lub automatyczne formatowanie po zapisie danego fragmentu. Postarajcie się na bieżąco formatować kod (nie tylko css, ale html i ts również). Schludność i estetyka są bardzo istotne i znacznie poprawiają czytelność, a jako że możemy o ten estetyczny aspekt zadbać w bardzo prosty sposób (edytor kodu robi to praktycznie za nas) to jest to wręcz must.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/app.component.html
> +  <app-navbar class="bar"></app-navbar>
Zamiast dodawać klasę "bar" możecie w templatce css'owej komponentu navbara użyć znacznika :host {}, w którym umieszczacie wszystkie propercje tej klasy.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/app.component.html
>  <!--<div *ngFor="let clock of clock$">-->
W trosce o czytelność i estetykę projektu nie powinno się wrzucać do głównej gałęzi zakomentowanych fragmentów kodu. Jeśli z jakiegoś powodu ten kod jest ekstremalnie ważny i musi zostać w projekcie to powinien mieć czytelny opis, dlaczego tutaj jest i do czego w przyszłości zostanie wykorzystany.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/app.component.ts
>    clock$: Clock;
Dlaczego to pole zawiera $?

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/app.component.ts
> +  // }
Jak wyżej. Staramy się unikać wrzucania zakomentowanego kodu.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.css
> +  .startRegistration {
Pisanie klas camel casem jest ryzykowne, ponieważ niektóre przeglądarki mogą nie rozróżniać wielkości liter, co może generować problemy. Dlatego warto używać tej samej wielkości liter dla klas w CSS. 
Najczęściej przeze mnie spotykaną jest konwencja z myślnikiem. 
Dodatkowym argumentem przeciwko camel case w CSS jest fakt, że dwie klasy wyżej został użyty "-", a skoro tak to powinno się już trzymać tej jednej konwencji.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.css
> +  .ClockInButton{
Nazwy klas nie powinno zaczynać się wielką literą, ze względu na problem opisany wyżej oraz fakt że odchodzi się od konwencji zastosowanej w większości klas pisanych małą literą.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.css
> +  .ClockOutButton{
jw.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +      <i class="material-icons" style="font-size:70px;">access_time</i>
Pisanie inline styli nie jest błędem, jednak może zostać odebrane jako oznaka niedbałości, dlatego że generujemy kod CSS'owy w templatce komponentu, który ma wyznaczony plik CSS, w którym znajdują się pozostałe style.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +     <i class="material-icons" style="font-size:70px;">access_time</i>
jw.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  constructor() { }
Jeżeli nie wykorzystujemy constructora to możemy go usunąć, dla czytelności

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  }
Jeżeli nie wykorzystujemy ngOnInit to możemy go usunąć, dla czytelności

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/data.service.ts
> +  }*/
Patrz komentarz powyżej dotyczący zakomentowanego kodu.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +
Zbędny odstęp

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +
Zbędny odstęp

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +}
Tutaj dla odmiany powinien zostać dodany odstęp

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +:root{
Główne style aplikacji powinny się znajdować w katalogu src w pliku styles.css

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +  font-size: 16px;
font-size: 16px jest wartością domyślną w większości przeglądarek, dlatego ta linijka jest zbędna. 
Jeśli chcemy, aby rozmiar czcionki wyglądał tak samo we wszystkich przeglądarkach to używajmy remów.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +  text-align:center;
Dlaczego centrujecie tekst domyślnie w całej aplikacji? Znacznik root odpowiada za główny element aplikacji.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +  height: 6em;
Sugestia: warto używać jednostki em, jeśli font-size parenta różni się od głównego font-size'u w aplikacji. W przeciwnym wypadku warto używać remów, łatwej się czyta taki kod. Jednostka em jest trudniejsza w interpretacji, dlatego że jej wartość zależy od specyficznych ustawień parenta, która może być różna w wielu miejscach, podczas gdy jednostka rem jest taka sama dla całej aplikacji.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +
Jeśli już używamy media queries to warto najpierw zastanowić się nad tym jakie chcemy mieć podejście do stosowania tego narzędzia w całej aplikacji?
- Możemy ustalić sobie swoje własne breakpointy (tak jak wyżej), co absolutnie nie jest błędem i być może sprawi, że aplikacja będzie maksymalnie dostosowana do naszych oczekiwań, jeśli chodzi o responsywność, jednak mieć na względzie, że takie podejście może mieć też swoje minusy i np. okazać się trudniejsze w utrzymaniu.
Można też skorzystać z zaproponowanych przez media query breakpointów wykorzystując wszystkie albo tylko niektóre z nich (w zależności od potrzeb) i mieć dzięki temu jakąś wspólną konwencję.
- Możemy używać zarówno min-width jak i max-width, jednak warto wiedzieć że takie rozwiązanie również może okazać się w dłuższej perspektywie trudniejsze w utrzymaniu. Możemy też skorzystać np. tylko z max-width i stylować poszczególne partie kodu kaskadowo.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +declare var require: any;
1. Przypuszczam, że ta zmienna nie jest używana, czyli nie powinno jej tutaj być
2. Jeśli już mamy potrzebę stworzyć taką zmienną to nie używamy var. 
Odsyłam do lektury: https://medium.com/better-programming/javascript-variables-the-difference-between-var-let-and-const-10efef5d2728

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +  $logo;
Dlaczego znów pole zawiera $? (co dziwne - dla odmiany tym razem na początku) Czy to jakaś naleciałość z PHP? Nie spotkałam się dotychczas z takim sposobem definiowania zmiennych w Angularze.

2020-08-12 21:53 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.html
> +  <li class="navbar-item"><a class="nav-link" href="#"><i class="material-icons" style="font-size:70px;">power_settings_new</i><span class="link-text">Wyloguj</span></a></li>
Mamy kod, który w większości powtarza się czterokrotnie. Zamiast tego możemy stworzyć sobie tablicę obiektów, które będą zawierały dwa pola np. iconName i title a następnie, aby wyświetlić te elementy - przeiterować sobie po tablicy używając *ngFor.

2020-08-13 06:52 UTC, Czadzik commented on src/app/app.component.css
> +.bar{
Całkiem zapomnieliśmy o formatowaniu kodu w css i html. Wszystko już sformatowane, na przyszłość postaramy się o tym nie zapominać ;)

2020-08-13 06:58 UTC, Czadzik commented on src/app/app.component.html
>  <!--<div *ngFor="let clock of clock$">-->
Tak, ten fragment kodu jest zbędny, już został usunięty.

2020-08-13 07:09 UTC, Czadzik commented on src/app/app.component.ts
>    clock$: Clock;
Jak sprawdzałem, w jaki sposób wyświetlić dane z api ktoś tak zadeklarował zmienna i po prostu uznałem, że tak ma być. Teraz okazało się, że to jakiś ewenement 😂.

2020-08-13 07:13 UTC, Czadzik commented on src/app/app.component.ts
> +  // }
Myślałem, że może się to jeszcze przydać. Wczoraj uznaliśmy, że będzie przychodził cały obiekt daty, wiec ten kod już znika.🙂

2020-08-13 08:21 UTC, jozek24 commented on src/app/dashboard/dashboard.component.css
> +  .startRegistration {
Okej, dobrze wiedzieć. Czyli najlepiej myślnik.

2020-08-13 08:37 UTC, jozek24 commented on src/app/dashboard/dashboard.component.html
> +      <i class="material-icons" style="font-size:70px;">access_time</i>
Zgadza się, przeniosłem to.

2020-08-13 20:13 UTC, ewelina-slepko requested changes
Jest już lepiej, ale znalazłam jeszcze kilka drobiazgów do poprawy.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/app.component.ts
> +    constructor(private  dataService: DataService) {
Fajnie jeszcze byłoby nazwać ten service bardziej precyzyjnie względem rodzaju danych jakie przechowuje oraz metod jakie posiada

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/clock.model.ts
> +    Second: number;
Nazwy pól w klasie powinny być z małej litery. Z wielkiej litery definiujemy tylko nazwy klas.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/data.service.spec.ts
> -import { TestBed } from '@angular/core/testing';
Ten plik służy do testów, dlatego na obecnym etapie rozwoju aplikacji można go usunąć, ponieważ nie jest wykorzystywany.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +    .NavBar {
Nazwa klasy powinna rozpoczynać się z małej litery, ze względu na problem opisany w poprzedniej pr'ce.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +    .NavBar {
Nazwa klasy powinna rozpoczynać się z małej litery, ze względu na problem opisany w poprzedniej pr'ce.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.html
> +                class="link-text">{{element.text}}</span></a></li>
Ten fragment kodu można sformatować bardziej czytelnie:

```html
<li class="navbar-item" *ngFor="let element of this.navbarArray">
   <a class="nav-link" href='{{element.icon}}'>
      <i class="material-icons">{{element.icon}}</i>
      <span class="link-text">{{element.text}}</span>
   </a>
</li>
```

Dobrze jest znaczniki zaczynać w nowej linii oraz - jeśli element ma dzieci - zamykać znacznik również w nowej linii, zwłaszcza jeśli mamy w nim elementy zagnieżdżone. Łatwiej jest się odnaleźć wtedy w gąszczu elementów w nim osadzonych, ponieważ wcięcia ładnie nam zaznaczają powiązania między elementami i trudniej jest przeoczyć element, który potencjalnie możemy chcieć znaleźć.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +    logo;
Pole nie ma określonego typu a powinno mieć.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +    navbarArray;
jw.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +    }
Jeśli kod jest nieużywany to starajmy się go usuwać.

2020-08-13 20:13 UTC, ewelina-slepko commented on src/styles.css
> +}
Ten plik nie jest sformatowany.

2020-08-17 13:42 UTC, ewelina-slepko requested changes

2020-08-17 13:42 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +    navbarArray;
pole navbarArray nadal nie ma typu

2020-08-17 13:42 UTC, ewelina-slepko commented on src/app/app.component.html
> +        </div>
Kod nie został sformatowany

2020-08-17 13:42 UTC, ewelina-slepko commented on src/app/app.component.ts
> +    constructor(private  dataService: ClockDataService) {
Tutaj również warto byłoby zmienić nazwę na odpowiadającą nazwie serwisu

2020-08-18 07:59 UTC, ewelina-slepko requested changes

2020-08-18 07:59 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.ts
> +    navBarArray: ({ link: string; icon: string; text: string })[];
Można to zapisać prościej. Do określania typów w Angularze wykorzystujemy interface lub klasę ( w zależności od potrzeb).  Warto w tym samym katalogu stworzyć sobie plik np. dtos.ts, który będzie służył nam do definiowania typów w danym komponencie. W tym przypadku definicja typu będzie wyglądała następująco:

export interface Navbar {
link: string; 
icon: string; 
text: string
}

A przypisanie typu: 
navbarArray: Navbar[]

2020-08-18 11:55 UTC, ewelina-slepko approved these changes

2020-08-18 12:08 UTC, merged