Post ClockIn and ClockOut to api.
Karmazynowe-Zyrafy/AngularWebClockClient pull request #2
Opened 2020-08-19 10:42 UTC by jozek24

2020-08-20 06:46 UTC, ewelina-slepko requested changes

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/Services/api.service.ts
> +  public PostClockIn(): Observable<HttpResponse<Response>> {
Dlaczego nazwa metody jest z wielkiej litery? Biorąc pod uwagę konwencję powinna być z małej

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/Services/api.service.ts
> +  public PostClockOut(): Observable<HttpResponse<Response>> {
jw

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  ClockIn(): void {
Nazwa metody znów jest z wielkiej litery

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  ClockOut(): void {
jw

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +      console.log(response);
Starajmy się nie wrzucać console.logów do głównego brancha, jeśli nie ma takiej potrzeby (jak np. podczas logowania errorów)

Ciekawostka. Funkcje strzałkowe umożliwiają nam stworzenie one linera, kiedy wewnątrz funkcji wykonujemy tylko jedną czynność, wtedy kod wygląda w taki sposób:

  ClockIn() {
    this.apiService.PostClockIn().subscribe(**response => console.log(response)**);
  }

2020-08-20 06:46 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +      console.log(response);
Fajnie byłoby w tym miejscu dodać jakąś notyfikację, żeby użytkownik wiedział o tym, że kliknięcie w button przyniosło zamierzone efekty, dobrze byłoby też wyświetlić dokładną godzinę zalogowania gdzieś pod spodem? 

Warto też od razu pomyśleć i zaimplementować mechanizm, który uniemożliwi użytkownikowi wielokrotne klikanie w ten sam przycisk zanim wybierze wylogowanie się.

2020-08-22 18:20 UTC, ewelina-slepko requested changes

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    ></ng-container>
Tworzymy tutaj ng-container, który nie zawiera żadnej wartości i wydaje się że ten fragment kodu powstał, tylko po to aby wykonać warunek else.  A gdyby zrezygować całkiem z tego fragmentu i... (patrz komentarz niżej)

(Na przyszłość: zamiast pisać warunek errorClockIn === null możemy napisać po prostu !errorClockIn)

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    </ng-template>
... tutaj dodać warunek, który mówi nam o tym, że chcemy wyświetlać ten fragment w przypadku, kiedy pole errorClockIn nie jest nullem? Czyli dokładnie to co mamy wyżej, tylko o kilka linijek kodu oraz jeden warunek mniej. Dodatkowo nie potrzebujemy ng-template (on i tak jest usuwany z DOMu), warunek możemy nanieść na paragraf.

```suggestion
      <p *ngIf="errorClockIn">Nie zarejestrować wejścia do pracy Error: {{ errorClockIn }}</p>
```

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    </ng-template>
Analogicznie do fragmentu kodu powyżej. ng-container z powyższym warunkiem, który nie zawiera żadnego kontentu jest zbyteczny. Dodajmy odpowiedni warunek dla fragmentu, który zawiera treść.

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +      <p>Nie zarejestrować wyjścia z pracy Error: {{ errorClockOut }}</p>
Fajnie byłoby też zamienić ten komunikat na bardziej czytelny dla użytkownika np. Brak możliwości zarejestrowania godziny wyjścia. Pamiętajmy, że front ma być przede wszystkim przyjazny użytkownikowi.

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  errorClockOut: number = null;
1. Pola w komponencie definiujemy powyżej constructora,
2. Null to domyślna wartość, jeśli niczego nie przypisujemy do danego pola, dlatego wystarczy zapisać to w taki sposób: 

```suggestion
  errorClockIn: number;
  errorClockOut: number;
  
  constructor(private apiService: ApiService) {}
```

2020-08-22 18:20 UTC, ewelina-slepko commented on src/app/Services/api.service.ts
> +    this.id = 1;
Sugestia: Dla tych trzech pól możemy przypisać wartość podczas definiowania, w tym przypadku nie musimy tego robić osobno w constructorze.

2020-08-24 09:50 UTC, ewelina-slepko requested changes

2020-08-24 09:50 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    </p>
Założenie, że otrzymamy zawsze status 404 to bardzo optymistyczne założenie. A co jeśli dostaniemy jakiś inny status (np. 401 lub 500)? Wtedy użytkownik nie otrzyma żadnej informacji. Powinniśmy założyć, że w przypadku otrzymania statusu innego niż 200 powinna się wyświetlać ta informacja: 

```suggestion
    <p *ngIf="errorClockIn !== 200">
      Wystąpił błąd Error: {{ errorClockIn }} nie udało się zarejestrować
      wejścia do pracy
    </p>
```

2020-08-24 09:50 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  errorClockOut: number;
Z kodu wynika, że do tego pola przypisujemy response.status, a status to status - nie error. Dlatego to pole powinno się nazywać względem tego co przechowuje np. statusClockIn i statusClockOut

2020-08-24 09:50 UTC, ewelina-slepko commented on src/app/Services/api.service.ts
> +    'https://localhost:44385/api/ClockInOut/BalanceToThisDay/';
we wszystkich czterech przypadkach powtarzamy kod https://localhost:44385/api. można ten fragment wrzucić do osobnego pola np. apiBaseUrl = https://localhost:44385/api/ a następnie zaimplementować ten fragment w pozostałych linkach.

```suggestion
  clockInUrl = `${this.apiBaseUrl}/ClockInOut/ClockIn/`;
  clockOutUrl = `${this.apiBaseUrl}/ClockInOut/ClockOut/`;
  balanceUrl = `${this.apiBaseUrl}/ClockInOut/Balance/`;
  BalanceToThisDayUrl =
    `${this.apiBaseUrl}/api/ClockInOut/BalanceToThisDay/`;
```
Jeśli mamy fragmenty kodu, które nam się powtarzają to starajmy się je zawsze opakowywać w reużywalne pola/metody. To ułatwia utrzymywanie aplikacji. Na przykładzie tego kodu - jeśli zechcemy zmienić localhost:44385 na jakiś inny port lub całkowicie inny adres to musielibyśmy zrobić to w czterech miejscach, a kiedy zapiszemy tą wartość w polu - wystarczy dokonać zmiany w jednym miejscu.

2020-08-24 09:50 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    </p>
jw

2020-08-24 11:14 UTC, ewelina-slepko requested changes

2020-08-24 11:14 UTC, ewelina-slepko commented on src/app/Services/api.service.ts
> +  BalanceToThisDayUrl = this.baseUrl + '/ClockInOut/BalanceToThisDay/';
Nie jest to błąd, aby tworzyć stringa za pomocą znaku "+", ale dobrze jest iść z postępem czasu i stosować aktualne narzędzia wprowadzone do Javascript (w tym przypadku ES6 - wprowadzone 5 lat temu, w którym doszły m.in backticki - przykład zastosowania dodałam w poprzednim code review pod tym fragmentem kodu). Podrzucam również przykładowy artykuł: 
https://jack.ofspades.com/multiline-strings-in-es6-javascript/

2020-08-24 11:14 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    <p *ngIf="responseStatusClockIn !== 200 && responseStatusClockIn !== null">
Zamiast pisać  !==null czy === null, wystarczy responseStatusClockIn i !responseStatusClockIn.

```suggestion
    <p *ngIf="responseStatusClockIn && responseStatusClockIn !== 200">
```

2020-08-24 11:14 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    >
jw

2020-08-24 11:14 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
Jak już kiedyś wcześniej wspomniałam, null jest domyślną wartością podczas definiowania jeśli nie przypisujemy żadnej wartości dlatego wystarczy

```suggestion
  responseStatusClockIn: number;
  responseStatusClockOut: number;
```

2020-08-24 11:47 UTC, Czadzik commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
A czy domyślną wartością nie jest undefined? Bez przypisanego nulla warunek nie mi działał. Można też warunek zmienić na undefined.

2020-08-24 12:55 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
Dlatego własnie zamiast w warunku sprawdzać czy określone pole jest nullem (tak jak w dashboard.component.html), możemy użyć sprawdzenia poprzez nazwaPola/!nazwaPola, co sprawdzi czy wartość w polu jest lub nie jest "falsy" (czyli NaN, null, undefined, empty string, 0n, -0, 0, false).

2020-08-24 13:03 UTC, Czadzik commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
Ok, już rozumiem dzięki 😉

2020-08-24 16:09 UTC, Czadzik commented on src/app/Services/api.service.ts
> +  BalanceToThisDayUrl = this.baseUrl + '/ClockInOut/BalanceToThisDay/';
Lubię "+" bo są uniwersalne chyba w prawie każdym języku. Ale rozumiem, że przy większych stringach może być to czytelniejsze. Zmieniłem tak jak poradziłaś 😉

2020-08-24 16:15 UTC, Czadzik commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
Skasowałem nadmiarowe inicjalizacje nullami. Niestety warunek z samym !responseStatusClockIn coś dalej mi nie działał, może jeszcze coś źle zrobiłem 😅. Na razie zostawiłem ze sprawdzaniem, czy nie jest undefined.

2020-08-25 06:49 UTC, ewelina-slepko reviewed
A jak wyglądał kod, który Ci nie działał? 
Aktualnie sprawdzasz: responseStatusClockIn !== 200 && responseStatusClockIn !== undefined, 
co można zastąpić: responseStatusClockIn && responseStatusClockIn !== 200;

2020-08-25 06:49 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.ts
> +  responseStatusClockOut: number = null;
Nie jest to oczywiście coś obowiązkowego, jeśli nie chcecie tego zmieniać może zostać. Jak wcześniej wspomniałam aktualne komentarze to sugestie dotyczące dobrych praktyk.

2020-08-25 06:52 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +    >
A jak wyglądał kod, który Ci nie działał? 
Aktualnie sprawdzasz: responseStatusClockIn !== 200 && responseStatusClockIn !== undefined, 
co można zastąpić: responseStatusClockIn && responseStatusClockIn !== 200;

2020-08-25 07:06 UTC, merged