Mobile version
Karmazynowe-Zyrafy/AngularWebClockClient pull request #9
Opened 2020-08-26 17:39 UTC by Czadzik

2020-08-26 20:57 UTC, ewelina-slepko requested changes

2020-08-26 20:57 UTC, ewelina-slepko commented on src/app/clock-in-out-history/clock-in-out-history.component.css
> +}
Sugestia: W moim odczuciu ten font-size jest za duży

2020-08-26 20:57 UTC, ewelina-slepko commented on src/app/dashboard/dashboard.component.html
> +      <p>Minuty Do Przepracowania: {{ balanceData.minutesLeft }}</p>
Tutaj fajnie byłoby zaprezentować dane w nieco bardziej skróconej formie:

```suggestion
      <p>Godziny Do Przepracowania: {{ balanceData.hoursLeft }}: {{ balanceData.minutesLeft }}</p>
```

2020-08-26 20:57 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +    display: unset;
Super, że użyłeś tej property :)

2020-08-26 20:57 UTC, ewelina-slepko commented on src/app/navbar/navbar.component.css
> +  font-size: 5rem;
W tym przypadku defaultowa wartość analogicznie powinna wynosić mniejszy font-size niż wartość font-size w zakresie min-width: 320px. Dlatego że pierwszy breakpoint to 320px, a jeśli wyświetlimy aplikację na urządzeniu, które ma 319px to aktualnie font-size będzie wynosił 5rem.

2020-08-27 06:56 UTC, Czadzik commented on src/app/dashboard/dashboard.component.html
> +      <p>Minuty Do Przepracowania: {{ balanceData.minutesLeft }}</p>
Te dane Józek już zmienił na swoim pr

2020-08-27 08:22 UTC, ewelina-slepko approved these changes

2020-08-27 08:26 UTC, merged